name: 02 - Workflow Events
on:
        workflow_dispatch:
        pull_request:

jobs:
    - name: Show the trigger
      runs-on: ubuntu-latest
      steps:
        - name: Show the trigger
          run: echo "The event type is ${{ github.event_name }}"
